# Site settings
title: Adones Reballos
email: adones.kjc@gmail.com
description: "This is going to be my portfolio page."
baseurl: ""
url: "http://dondonai.github.io"
twitter_username: dondonai
github_username:  dondonai

# Build settings
markdown: kramdown
permalink: pretty
